export {default as Loader} from "./Loader.jsx"
export {default as Footer} from "./Footer.jsx"
export {default as Navbar} from "./Navbar.jsx"
export {default as Services} from "./Services.jsx"
export {default as Transactions} from "./Transactions.jsx"
export {default as Welcome} from "./Welcome.jsx"